name: AOC
version: 0.0.1
synopsis: Advent of code solutions for 2022
description: See README at <https://github.com/japiirainen/aoc-2022#readme>
maintainer: Joona Piirainen <joona.piirainen@gmail.com>
github: japiirainen/aoc-2022

ghc-options: 
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-deprecations

default-extensions:
  - LambdaCase 
  - DeriveFunctor
  - BangPatterns
  - BlockArguments
  - TypeOperators
  - TypeFamilies
  - DeriveGeneric
  - DeriveFoldable
  - NumericUnderscores
  - OverloadedStrings
  - TypeApplications
  - DerivingStrategies
  - ViewPatterns
  - GeneralizedNewtypeDeriving
  - RankNTypes
  - ScopedTypeVariables
  - UnicodeSyntax
  - DataKinds
  - GADTs
  # records
  - RecordWildCards
  - OverloadedRecordDot
  - NoFieldSelectors

dependencies:
  - base
  - mtl
  - containers
  - pretty
  - text
  - directory
  - selective
  - vector
  - array
  - linear
  - safe
  - unordered-containers
  - MemoTrie
  - lens
  - split
  - foldl
  - sbv
  - streams
  - async

library:
  source-dirs: 
    - lib
  exposed-modules:
    - AOC.List.Transformer
    - AOC.List.Extended
    - AOC.Box
    - AOC.Nat
    - AOC.Parser
    - AOC.V2
    - AOC.V3
    - AOC.V2.Box
    - AOC.Grid
    - AOC.Main
    - AOC.Foldable
    - AOC.Dijkstra
    - AOC.Vector.Extra
    - AOC.Grid.Bounded
    - AOC.Functor.Fix
    - AOC.Coord
    - AOC.Test
    - AOC.Search
    - AOC.Queue

executables:
  01:
    source-dirs: "src"
    main: 01.hs
    dependencies: AOC
  02:
    source-dirs: "src"
    main: 02.hs
    dependencies: AOC
  03:
    source-dirs: "src"
    main: 03.hs
    dependencies: AOC
  04:
    source-dirs: "src"
    main: 04.hs
    dependencies: AOC
  05:
    source-dirs: "src"
    main: 05.hs
    dependencies: AOC
  06:
    source-dirs: "src"
    main: 06.hs
    dependencies: AOC
  07:
    source-dirs: "src"
    main: 07.hs
    dependencies: AOC
  08:
    source-dirs: "src"
    main: 08.hs
    dependencies: AOC
  09:
    source-dirs: "src"
    main: 09.hs
    dependencies: AOC
  10:
    source-dirs: "src"
    main: 10.hs
    dependencies: AOC
  11:
    source-dirs: "src"
    main: 11.hs
    dependencies: AOC
  12:
    source-dirs: "src"
    main: 12.hs
    dependencies: AOC
  13:
    source-dirs: "src"
    main: 13.hs
    dependencies: AOC
  14:
    source-dirs: "src"
    main: 14.hs
    dependencies: AOC
  15:
    source-dirs: "src"
    main: 15.hs
    dependencies: AOC
  16:
    source-dirs: "src"
    main: 16.hs
    dependencies: AOC
  17:
    source-dirs: "src"
    main: 17.hs
    dependencies: AOC
  18:
    source-dirs: "src"
    main: 18.hs
    dependencies: AOC
  19:
    source-dirs: "src"
    main: 19.hs
    dependencies: AOC
  20:
    source-dirs: "src"
    main: 20.hs
    dependencies: AOC
  21:
    source-dirs: "src"
    main: 21.hs
    dependencies: AOC
  23:
    source-dirs: "src"
    main: 23.hs
    dependencies: AOC
  24:
    source-dirs: "src"
    main: 24.hs
    dependencies: AOC
  25:
    source-dirs: "src"
    main: 25.hs
    dependencies: AOC
